# Generated by Django 4.2.20 on 2025-05-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='patient',
        ),
    ]
